version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gram_sabha_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gram_sabha_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gram_sabha_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gram_sabha_db
      - UPLOAD_DIR=/app/uploads
      - AI_MOCK_MODE=True
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: gram_sabha_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
  uploads_data:
